# Generated by Django 5.0.1 on 2024-06-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='name',
        ),
    ]
